using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace darwin.Entities;

public class RefreshToken : BaseEntity<Guid>
{
    // - this token property is the so called refreshtoken
    // - this token of the refreshtoken is autogenerated by db see corresponding EntityTypeConfiguration of the database
    public string Token { get; set; } = string.Empty;

    public string JwtId { get; set; } = string.Empty;

    public DateTime Created { get; set; }

    public DateTime ExpirationDate { get; set; }

    public bool Used { get; set; }

    public bool Invalidated { get; set; }

    public Guid UserId { get; set; }

    public AppUser User { get; set; } = null!;
}