using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace hello_asp_identity.Domain;

public class RefreshToken
{
    // - this token property is the so called refreshtoken
    // - this token of the refreshtoken is autogenerated by db see corresponding EntityTypeConfiguration of the database
    // - Token is PrimaryKey of RefreshToken
    public string Token { get; set; }

    public string JwtId { get; set; }

    public DateTime Created { get; set; }

    public DateTime ExpirationDate { get; set; }

    public bool Used { get; set; }

    public bool Invalidated { get; set; }

    public Guid UserId { get; set; }

    public AppUser User { get; set; }
}